name: ci-mlops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-package-smoke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package final model
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m scripts.package_final_model

    - name: Smoke inference
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m scripts.smoke_inference